#!/usr/bin/env node

let exec = require("child_process").exec,
	util = require("util"),
	fs = require("fs"),
	contents = null,
	branch,
	desc;

if (/COMMIT_EDITMSG/g.test(process.argv[2])) {
	branch = exec("git branch | grep '*'", function (err, stdout, stderr) {
		if (err) {
			process.exit(0);
		}

		contents = fs.readFileSync(process.argv[2]);
		const name = stdout.replace("* ", "").replace("\n", "");
		const link = `http://jiralink.com/${name}`;

		desc = exec(
			"git config branch." + name + ".description",
			function (err, stdout, stderr) {
				if (name !== "(no branch)") {
					contents = util.format(
						"\n",
						`\n${name}`,
						`\n${link}`,
						`\n${contents}`
					);
					fs.writeFileSync(process.argv[2], contents);
					process.exit(0);
				} else {
					process.exit(0);
				}
			}
		);
	});
}
